version: '3.8'
services:
  client-backend:
    platform: linux/arm64
    image: mitroshinevgeniy/mylibrarybook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/books_db

  postgres:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Arsenal111
      ports:
        - "5432:5432"
      volumes:
        - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
        - /Users/mitrosin.evgeniy/ImageDockerApp/PostgreSQL/db-data:/var/lib/postgresql/data
      restart: unless-stopped

  pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      volumes:
        - /Users/mitrosin.evgeniy/ImageDockerApp/PostgreSQL/pgadmin-data:/var/lib/pgadmin
